language: ruby

rvm: "1.9.2"

# uncomment this line if your project needs to run something other than `rake`:
bundler_args: --without development production

before_script: RAILS_ENV=test bundle exec rake db:reset

script: bundle exec rspec --format documentation

notifications:
  recipients:
  	- christophersbunting@gmail.com